### ISSUE TITLE
More SVG Layers

### ISSUE THREAD

**Issue by jbonisteel** [FirefoxGraphics/wr-planning#68] opened 2020-02-03 20:08 UTC

**Comment by Gankra** [comment] 2020-02-13 18:06
I think this is just a dupe of #56 (https://bugzilla.mozilla.org/show_bug.cgi?id=1595799)

@jrmuizel confirmed?

**Comment by jrmuizel** [comment] 2020-02-13 19:31
Confirmed.

**Closed as completed by jrmuizel** 2020-02-13 19:31 UTC
